name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install client dependencies
      working-directory: ./client
      run: npm ci
    
    - name: Build client
      working-directory: ./client
      run: npm run build
    
    - name: Install server dependencies
      working-directory: ./server
      run: npm ci
    
    - name: Build server
      working-directory: ./server
      run: npm run build
    
    - name: Build Docker image
      run: docker build -t my-fullstack-app .
    
    - name: Push Docker image to registry
      run: |
        echo "${{ secrets.sandeepsingh }}" | docker login -u "${{ secrets.sandeepsingh }}" --password-stdin
        docker push my-fullstack-app:latest
